### ISSUE TITLE
Accessing weechat console

### ISSUE THREAD

**Issue by predkambrij** [dancek/docker-hthartk#1]
Hi.

Thanks for sharing your stuff. However, I had trouble accessing weechat console using "docker exec -it dockerdefault_weechat_1 tmux attach". It did nothing, but at the same time crashed the running container.

This is my workaround:
- start the container as described: ENTRYPOINT ["tmux", "new-session", "weechat"]
- access weechat console like this: docker exec -it dockerdefault_weechat_1 script /dev/null -c "tmux attach"

Br

**Comment by dancek** [comment]
Thanks for the feedback!

I don't quite understand why this would happen, but I'll document your workaround in README in case it helps someone else.

**Comment by predkambrij** [comment]
If I understand correctly, it is because tty is started outside of the container, but screen and tmux need it for some reason.

```
$ docker exec -it u14devgen1 bash
root@devgen1:/# tty
not a tty
root@devgen1:/# exit
 docker exec -it u14devgen1 script /dev/null -c bash
Script started, file is /dev/null
root@devgen1:/# tty
/dev/pts/3
root@devgen1:/#

$ docker exec -it u14devgen1 bash
root@devgen1:/# screen
Must be connected to a terminal.
root@devgen1:/# exit
$ docker exec -it u14devgen1 bash
root@devgen1:/# tmux
root@devgen1:/# echo $?
1
```

**Comment by dancek** [comment]
That explains it, but somehow I have a tty.

```
$ docker exec -it dockerdefault_weechat_1 sh
/ # tty
/dev/pts/2
```

**Comment by dancek** [comment]
Looks like there's an open Docker issue about this: docker/docker#8755

I can't be bothered to read through the specifics, but it seems to work for some people and not for others. :)

**Comment by predkambrij** [comment]
I reproduced the bug. I used ubuntu:14.04.3 instead of alpine:3.3 and there are differences about tty in those two distros (like ubuntu and centos https://github.com/docker/docker/issues/8755#issuecomment-158815738).

```
$ docker run -it --name=test1 gliderlabs/alpine:3.3 sh
/ # apk-install tmux
...
/ # tty
/11
/ # tmux new
<ok>
$ docker exec -it test1 tty
/dev/pts/10
docker exec -it test1 tmux attach
<works as expected>

docker run -it --rm --name=utest1 ubuntu:14.04.3 bash
root@166de1248c73:/# tty
/dev/console
root@166de1248c73:/# apt-get install tmux
...
root@166de1248c73:/# tmux new
<works>

$ docker exec -it utest1 tty
not a tty
docker exec -it utest1 tmux attach
<crashes the running tmux>
```

So the workaround is needed only for some base images. Btw, screen is broken in alpine (it crashes with this error message), but you can get it working with workaround (install util-linux that script command gets available).

```
docker run -it --name=test1 gliderlabs/alpine:3.3 sh
...
/ # screen
Cannot access '/10': No such file or directory
$ docker exec -it test1 screen
Cannot access '/dev/pts/9': No such file or directory
```
